version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: test_api
      POSTGRES_USER: test2024
      POSTGRES_PASSWORD: test2024!
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: